##
## SPDX-FileCopyrightText: 2023 Splunk, Inc. <sales@splunk.com>
## SPDX-License-Identifier: LicenseRef-Splunk-8-2021
##
##

[defender_advanced_hunting]
python.version = python3
description = Defender Advanced Hunting
label = Defender Advanced Hunting
param._cam = {"technology": [{"vendor": "Microsoft", "product": "Defender", "version": ["2.3.0"]}], "supports_adhoc": true, "category": ["threat hunting"], "task": ["hunt"], "subject": ["threat hunting"]}
is_custom = 1
payload_format = json
icon_path = alert_defender_advanced_hunting.png

[defender_update_incident]
python.version = python3
description = Update a Defender incident
label = Defender Update Incident
is_custom = 1
payload_format = json
icon_path = alert_defender_update_incident.png

[defender_update_incident_graph]
python.version = python3
description = Update a Defender incident using the Microsoft Graph API
label = Defender Update Incident via Graph API
is_custom = 1
payload_format = json
icon_path = alert_defender_update_incident_graph.png
