##
## SPDX-FileCopyrightText: 2023 Splunk, Inc. <sales@splunk.com>
## SPDX-License-Identifier: LicenseRef-Splunk-8-2021
##
##
[install]
state_change_requires_restart = false
is_configured = false
state = enabled
build = 1742448928

[launcher]
author = Splunk, Inc.
version = 2.3.3
description = Splunk Add-on for Microsoft Security

[ui]
is_visible = true
label = Splunk Add-on for Microsoft Security
docs_section_override = AddOns:released

[package]
id = Splunk_TA_MS_Security
check_for_updates = true

[triggers]
reload.splunk_ta_ms_security_account = simple
reload.splunk_ta_ms_security_settings = simple

[id]
name = Splunk_TA_MS_Security
version = 2.3.3
