##
## SPDX-FileCopyrightText: 2021 Splunk, Inc. <sales@splunk.com>
## SPDX-License-Identifier: LicenseRef-Splunk-8-2021
##
##
[ms_security_incident]
search = (sourcetype=ms365:defender:incident)
#tags ticketing incident

[ms_security_atp_alert]
search = (sourcetype=ms:defender:atp:alerts)
#tags alert

[ms_security_advanced_hunting]
search = sourcetype="m365:defender:incident:advanced_hunting"

[ms_security_advanced_hunting_process]
search = eventtype="ms_security_advanced_hunting" $table="DeviceProcessEvents" OR $table="DeviceEvents" OR $table="DeviceImageLoadEvents" OR $table="DeviceNetworkEvents"
#tags process report

[ms_security_advanced_hunting_filesystem]
search = eventtype="ms_security_advanced_hunting" $table="DeviceFileEvents"
#tags endpoint filesystem

[ms_security_advanced_hunting_registry]
search = eventtype="ms_security_advanced_hunting" $table="DeviceRegistryEvents"
#tags endpoint registry

[ms_security_advanced_hunting_delivery]
search = eventtype="ms_security_advanced_hunting" $table="EmailPostDeliveryEvents"
#tags email delivery

[ms_security_advanced_hunting_email]
search = eventtype="ms_security_advanced_hunting" $table="EmailEvents"
#tags email

[ms_security_advanced_hunting_authentication]
search = eventtype="ms_security_advanced_hunting" $table="IdentityLogonEvents" OR $table="DeviceLogonEvents" OR $table="IdentityQueryEvents"
#tags authentication default

[ms_security_incident_alerts]
search = sourcetype=ms365:defender:incident:alerts
#tags alert

[ms_security_simulations]
search = sourcetype=ms:defender:simulations
#tags alert

[ms_security_eventhub_process]
search = sourcetype=ms:defender:eventhub category="AdvancedHunting-DeviceProcessEvents" OR category="AdvancedHunting-DeviceNetworkEvents" OR category="AdvancedHunting-DeviceLogonEvents" OR category="AdvancedHunting-DeviceEvents"
#tags process report

[ms_security_eventhub_filesystem]
search = sourcetype=ms:defender:eventhub category="AdvancedHunting-DeviceFileEvents" OR category="AdvancedHunting-DeviceImageLoadEvents"
#tags endpoint filesystem

[ms_security_eventhub_registry]
search = sourcetype=ms:defender:eventhub category="AdvancedHunting-DeviceRegistryEvents"
#tags endpoint registry

[ms_security_eventhub_certificate]
search = sourcetype=ms:defender:eventhub category="AdvancedHunting-DeviceFileCertificateInfo"
#tags certificate ssl

[ms_security_eventhub_network]
search = sourcetype=ms:defender:eventhub category="AdvancedHunting-DeviceNetworkInfo"
#tags inventory network

[ms_security_eventhub_os]
search = sourcetype=ms:defender:eventhub category="AdvancedHunting-DeviceInfo"
#tags inventory system version
