##
## SPDX-FileCopyrightText: 2023 Splunk, Inc. <sales@splunk.com>
## SPDX-License-Identifier: LicenseRef-Splunk-8-2021
##
##
[microsoft_365_defender_endpoint_incidents]
start_by_shell = false
python.version = python3
sourcetype = ms365:defender:incident
interval = 300
disabled = 0
environment = commercial

[microsoft_defender_endpoint_atp_alerts]
start_by_shell = false
python.version = python3
sourcetype = ms:defender:atp:alerts
interval = 300
location = api.securitycenter.windows.com
disabled = 0

[microsoft_defender_endpoint_machines]
start_by_shell = false
python.version = python3
sourcetype = ms:defender:machines
interval = 300
location = api.securitycenter.windows.com
disabled = 0

[ms_defender_endpoint_apt_alerts]
start_by_shell = false
sourcetype = ms:defender:atp
interval = 300
disabled = 0

[microsoft_defender_endpoint_simulations]
start_by_shell = false
python.version = python3
sourcetype = ms:defender:simulations
interval = 2629800
disabled = 0
environment = commercial-graph-api

[microsoft_defender_event_hub]
start_by_shell = false
python.version = python3
sourcetype = ms:defender:eventhub
consumer_group = $Default
streaming_event_types = AlertInfo,AlertEvidence,DeviceInfo,DeviceNetworkInfo,DeviceProcessEvents,DeviceNetworkEvents,DeviceFileEvents,DeviceRegistryEvents,DeviceLogonEvents,DeviceImageLoadEvents,DeviceEvents,DeviceFileCertificateInfo,EmailAttachmentInfo,EmailEvents,EmailPostDeliveryEvents,EmailUrlInfo,IdentityLogonEvents,IdentityQueryEvents,IdentityDirectoryEvents,CloudAppEvents
interval = 0
disabled = 0

### NEW - Microsoft Graph Security Advanced Hunting modular input
### Endpoint: POST https://graph.microsoft.com/v1.0/security/runHuntingQuery
[microsoft_graph_security_hunting_query]
start_by_shell = false
python.version = python3
sourcetype = ms:defender:hunting:query
interval = 300
disabled = 0
environment = commercial-graph-api

# the below two stanzas are MS Advance Hunt results written to stash
[batch://$SPLUNK_HOME/var/spool/splunk/...stash_ms_advance_hunt]
queue = stashparsing
sourcetype = stash_ms_advance_hunt
move_policy = sinkhole
crcSalt = <SOURCE>

[batch://$SPLUNK_HOME\var\spool\splunk\...stash_ms_advance_hunt]
queue = stashparsing
sourcetype = stash_ms_advance_hunt
move_policy = sinkhole
crcSalt = <SOURCE>

# the below two stanzas are MS Updated Incidents and associated Alerts written to stash
[batch://$SPLUNK_HOME/var/spool/splunk/...stash_ms_update_incident]
queue = stashparsing
sourcetype = stash_ms_update_incident
move_policy = sinkhole
crcSalt = <SOURCE>

[batch://$SPLUNK_HOME\var\spool\splunk\...stash_ms_update_incident]
queue = stashparsing
sourcetype = stash_ms_update_incident
move_policy = sinkhole
crcSalt = <SOURCE>

[script://$SPLUNK_HOME/etc/apps/Splunk_TA_MS_Security/bin/ms_security_encrypt_creds.py]
passAuth = admin
python.version = python3
interval = -1
# Enable this scripted input only when the GUI on HF is disabled to encrypt the credentials configured in MS Security TA's .conf files.
disabled = 1
