##
## SPDX-FileCopyrightText: 2021 Splunk, Inc. <sales@splunk.com>
## SPDX-License-Identifier: LicenseRef-Splunk-8-2021
##
##
[defender_index]
definition = index=main
iseval = 0

[defender_atp_index]
definition = index=main
iseval = 0
