
[admin:Splunk_TA_MS_Security]
match = /
members = Splunk_TA_MS_Security_account, Splunk_TA_MS_Security_settings, Splunk_TA_MS_Security_microsoft_365_defender_endpoint_incidents, Splunk_TA_MS_Security_microsoft_defender_endpoint_atp_alerts, Splunk_TA_MS_Security_microsoft_defender_endpoint_simulations, Splunk_TA_MS_Security_microsoft_defender_event_hub, Splunk_TA_MS_Security_microsoft_defender_endpoint_machines, Splunk_TA_MS_Security_microsoft_graph_security_hunting_query

[admin_external:Splunk_TA_MS_Security_account]
handlertype = python
python.version = python3
handlerfile = Splunk_TA_MS_Security_rh_account.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:Splunk_TA_MS_Security_settings]
handlertype = python
python.version = python3
handlerfile = Splunk_TA_MS_Security_rh_settings.py
handleractions = edit, list
handlerpersistentmode = true

[admin_external:Splunk_TA_MS_Security_microsoft_365_defender_endpoint_incidents]
handlertype = python
python.version = python3
handlerfile = Splunk_TA_MS_Security_rh_microsoft_365_defender_endpoint_incidents.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:Splunk_TA_MS_Security_microsoft_defender_endpoint_atp_alerts]
handlertype = python
python.version = python3
handlerfile = Splunk_TA_MS_Security_rh_microsoft_defender_endpoint_atp_alerts.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:Splunk_TA_MS_Security_microsoft_defender_endpoint_simulations]
handlertype = python
python.version = python3
handlerfile = Splunk_TA_MS_Security_rh_microsoft_defender_endpoint_simulations.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:Splunk_TA_MS_Security_microsoft_defender_event_hub]
handlertype = python
python.version = python3
handlerfile = Splunk_TA_MS_Security_rh_microsoft_defender_event_hub.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:Splunk_TA_MS_Security_microsoft_defender_endpoint_machines]
handlertype = python
python.version = python3
handlerfile = Splunk_TA_MS_Security_rh_microsoft_defender_endpoint_machines.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

### NEW - REST handler for Microsoft Graph Security Hunting Query input
[admin_external:Splunk_TA_MS_Security_microsoft_graph_security_hunting_query]
handlertype = python
python.version = python3
handlerfile = Splunk_TA_MS_Security_rh_microsoft_graph_security_hunting_query.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[script:get_delegated_usr_login]
python.version = python3
match = /get_login_url
handler=get_delegated_usr_login.LoginURL

[script:get_delegated_auth_token]
python.version = python3
match = /get_auth_token
handler=get_delegated_auth_token.DelegatedAuthToken
