##
## SPDX-FileCopyrightText: 2021 Splunk, Inc. <sales@splunk.com>
## SPDX-License-Identifier: LicenseRef-Splunk-8-2021
##
##
[eventtype=ms_security_atp_alert]
alert = enabled

[eventtype=ms_security_incident]
ticketing = enabled
incident = enabled

[eventtype=ms_security_advanced_hunting_process]
process = enabled
report = enabled

[eventtype=ms_security_advanced_hunting_filesystem]
endpoint = enabled
filesystem = enabled

[eventtype=ms_security_advanced_hunting_registry]
endpoint = enabled
registry = enabled

[eventtype=ms_security_advanced_hunting_delivery]
email = enabled
delivery = enabled

[eventtype=ms_security_advanced_hunting_email]
email = enabled

[eventtype=ms_security_advanced_hunting_authentication]
authentication = enabled
default = enabled

[eventtype=ms_security_incident_alerts]
alert = enabled

[eventtype=ms_security_simulations]
alert = enabled

[eventtype=ms_security_eventhub_process]
process = enabled
report = enabled

[eventtype=ms_security_eventhub_filesystem]
endpoint = enabled
filesystem = enabled

[eventtype=ms_security_eventhub_registry]
endpoint = enabled
registry = enabled

[eventtype=ms_security_eventhub_certificate]
certificate = enabled
ssl = enabled

[eventtype=ms_security_eventhub_network]
inventory = enabled
network = enabled

[eventtype=ms_security_eventhub_os]
inventory = enabled
system = enabled
version = enabled
