##
## SPDX-FileCopyrightText: 2021 Splunk, Inc. <sales@splunk.com>
## SPDX-License-Identifier: LicenseRef-Splunk-8-2021
##
##
[ms_security-process-process_path_no_filename]
SOURCE_KEY = FolderPath
REGEX = (?<process_path_no_filename>.*)[\/\/\\]+.[a-zA-Z.]*

[ms_security-process-process_name_args]
SOURCE_KEY = ProcessCommandLine
#REGEX = (?<process_name_extracted>^[\s\t]*(?:[^\s\t"\r\n]+|"[^"]+(?:"|$))+)(?<process_args>.+)?
REGEX = ((?<process_name_extracted>^[\s\t]*(?:[^\s\t"\r\n]+|"[^"]+(?:"|$))+)\s(?<process_args>.+)?|(?:(?<process_args2>.+)))

[ms_security-process-parent_process_path_no_filename]
SOURCE_KEY = InitiatingProcessFolderPath
REGEX = (?<parent_process_path_no_filename>.*)[\/\\]

[ms_security-process-parent_process_name_args]
SOURCE_KEY = InitiatingProcessCommandLine
#REGEX = (?<parent_process_name_extracted>^[\s\t]*(?:[^\s\t"\r\n]+|"[^"]+(?:"|$))+)(?<parent_process_args>.+)?
REGEX = ((?<parent_process_name_extracted>^[\s\t]*(?:[^\s\t"\r\n]+|"[^"]+(?:"|$))+)\s(?<parent_process_args>.+)?|(?:(?<parent_process_args2>.+)))

[recipient_domain_from_RecipientEmailAddress]
SOURCE_KEY = RecipientEmailAddress
REGEX = @(?<recipient_domain>[^@]+)

[dns_from_DnsAddresses]
SOURCE_KEY = properties.DnsAddresses
REGEX = \[\"(?<dns>[^\"]+)\".+

[ip_from_IPAddresses]
SOURCE_KEY = properties.IPAddresses
REGEX = \[\{\"IPAddress\":\"(?<ip>[^\"]+)\".+

[src_ip_from_DefaultGateways]
SOURCE_KEY = properties.DefaultGateways
REGEX = \[\"(?<src_ip>[^\"]+)\".+

[orig_action_name_for_stash_cam]
REGEX    = \*{3}Common\sAction\sModel\*{3}.*orig_action_name=\"([^"]+)
FORMAT   = $0 orig_action_name::$1
DEST_KEY = _meta

[orig_sid_for_stash_cam]
REGEX    = \*{3}Common\sAction\sModel\*{3}.*orig_sid=\"([^"]+)
FORMAT   = $0 orig_sid::$1
DEST_KEY = _meta

[orig_rid_for_stash_cam]
REGEX    = \*{3}Common\sAction\sModel\*{3}.*orig_rid=\"([^"]+)
FORMAT   = $0 orig_rid::$1
DEST_KEY = _meta

[sourcetype_for_stash_cam]
REGEX    = \*{3}Common\sAction\sModel\*{3}.*sourcetype=\"([^"]+)
FORMAT   = sourcetype::$1
DEST_KEY = MetaData:Sourcetype

[sinkhole_cam_header]
REGEX     = (?s)^\*{3}Common\sAction\sModel\*{3}[^\n]+\n(.*)
FORMAT    = $1
DEST_KEY  = _raw
## Do not truncate _raw to 4096!
LOOKAHEAD = -1

[ms_security_err_codes]
batch_index_query = 0
case_sensitive_match = 1
default_match = Unable to provide an ActionItem right now. Pleas re-check your configurations or try contacting Splunk support.
filename = ms_security_error_codes_210.csv
min_matches = 1
