##
## SPDX-FileCopyrightText: 2021 Splunk, Inc. <sales@splunk.com>
## SPDX-License-Identifier: LicenseRef-Splunk-8-2021
##
##

[expose:Splunk_TA_MS_Security_account]
pattern = Splunk_TA_MS_Security_account
methods = POST, GET

[expose:Splunk_TA_MS_Security_account_specified]
pattern = Splunk_TA_MS_Security_account/*
methods = POST, GET, DELETE

[expose:Splunk_TA_MS_Security_settings]
pattern = Splunk_TA_MS_Security_settings
methods = POST, GET

[expose:Splunk_TA_MS_Security_settings_specified]
pattern = Splunk_TA_MS_Security_settings/*
methods = POST, GET, DELETE

[expose:Splunk_TA_MS_Security_microsoft_365_defender_endpoint_incidents]
pattern = Splunk_TA_MS_Security_microsoft_365_defender_endpoint_incidents
methods = POST, GET

[expose:Splunk_TA_MS_Security_microsoft_365_defender_endpoint_incidents_specified]
pattern = Splunk_TA_MS_Security_microsoft_365_defender_endpoint_incidents/*
methods = POST, GET, DELETE

[expose:Splunk_TA_MS_Security_microsoft_365_defender_advanced_hunting]
pattern = Splunk_TA_MS_Security_microsoft_365_defender_advanced_hunting
methods = POST, GET

[expose:Splunk_TA_MS_Security_microsoft_365_defender_advanced_hunting_specified]
pattern = Splunk_TA_MS_Security_microsoft_365_defender_advanced_hunting/*
methods = POST, GET, DELETE

[expose:Splunk_TA_MS_Security_microsoft_defender_endpoint_atp_alerts]
pattern = Splunk_TA_MS_Security_microsoft_defender_endpoint_atp_alerts
methods = POST, GET

[expose:Splunk_TA_MS_Security_microsoft_defender_endpoint_atp_alerts_specified]
pattern = Splunk_TA_MS_Security_microsoft_defender_endpoint_atp_alerts/*
methods = POST, GET, DELETE

[expose:Splunk_TA_MS_Security_microsoft_defender_endpoint_machines]
pattern = Splunk_TA_MS_Security_microsoft_defender_endpoint_machines
methods = POST, GET

[expose:Splunk_TA_MS_Security_microsoft_defender_endpoint_machines_specified]
pattern = Splunk_TA_MS_Security_microsoft_defender_endpoint_machines/*
methods = POST, GET, DELETE

[expose:Splunk_TA_MS_Security_microsoft_defender_endpoint_simulations]
pattern = Splunk_TA_MS_Security_microsoft_defender_endpoint_simulations
methods = POST, GET

[expose:Splunk_TA_MS_Security_microsoft_defender_endpoint_simulations_specified]
pattern = Splunk_TA_MS_Security_microsoft_defender_endpoint_simulations/*
methods = POST, GET, DELETE

[expose:Splunk_TA_MS_Security_microsoft_defender_event_hub]
pattern = Splunk_TA_MS_Security_microsoft_defender_event_hub
methods = POST, GET

[expose:Splunk_TA_MS_Security_microsoft_defender_event_hub_specified]
pattern = Splunk_TA_MS_Security_microsoft_defender_event_hub/*
methods = POST, GET, DELETE

[expose:_splunkd_data]
pattern = data/*
methods = GET

[expose:get_delegated_usr_login]
pattern = get_login_url
methods = GET

[expose:get_delegated_auth_token]
pattern = get_auth_token
methods = GET
